# Generated by Django 6.0.1 on 2026-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(default=1, max_length=50, verbose_name="Токен"),
            preserve_default=False,
        ),
    ]
