# Generated by Django 6.0.1 on 2026-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(max_length=150, verbose_name="Токен"),
        ),
    ]
