# Generated by Django 6.0.1 on 2026-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "heading",
                    models.CharField(
                        help_text="Заголовок поста блога", max_length=150, unique=True, verbose_name="Заголовок"
                    ),
                ),
                ("content", models.TextField(blank=True, help_text="Текст поста блога")),
                (
                    "photo_blog",
                    models.ImageField(
                        blank=True, help_text="Фотография блога", upload_to="photo/", verbose_name="Фотография блога"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Дата создания поста", verbose_name="Дата создания поста"
                    ),
                ),
                (
                    "ispublication",
                    models.BooleanField(default=False, help_text="Опубликовано", verbose_name="Опубликовано"),
                ),
                (
                    "number_views",
                    models.IntegerField(
                        default=0, help_text="Количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
        ),
    ]
