# Generated by Django 6.0.1 on 2026-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, help_text="Текст поста блога", verbose_name="Текст блога"),
        ),
    ]
