# Generated by Django 6.0.1 on 2026-03-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["heading"], "verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
    ]
