# Generated by Django 6.0.1 on 2026-02-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование категории товаров",
                        max_length=200,
                        unique=True,
                        verbose_name="Катеория",
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Описание категории товаров")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Название товара", max_length=200, unique=True, verbose_name="Товар"),
                ),
                ("description", models.TextField(blank=True, help_text="Описание товара")),
                ("photo_product", models.ImageField(blank=True, upload_to="photo/", verbose_name="Фотография товара")),
                ("price", models.FloatField(default=0, verbose_name="Цена")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата занесения")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="Дата изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="catalog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
    ]
