# Generated by Django 6.0.1 on 2026-03-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Категория товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, help_text="Дата занесения товара", verbose_name="Дата занесения"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo_product",
            field=models.ImageField(
                blank=True, help_text="Фотография товара", upload_to="photo/", verbose_name="Фотография товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0, help_text="Цена товара", verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(auto_now=True, help_text="Дата изменения товара", verbose_name="Дата изменения"),
        ),
    ]
