# Generated by Django 6.0.1 on 2026-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number_views",
            field=models.IntegerField(
                default=0, help_text="Количество просмотров", verbose_name="Количество просмотров"
            ),
        ),
    ]
