# Generated by Django 6.0.1 on 2026-04-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_number_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="ispublication",
            field=models.BooleanField(default=True, help_text="Опубликовано", verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец продукта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
